<table cellpadding="0" cellspacing="0" class="Lista">
    <thead>
        <tr>
            <th colspan="2">Dados</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="text-align: left">Nome:</td>
            <td style="text-align: left"><?= $this->dados["nome"] ?></td>
        </tr>
        <tr>
            <td style="text-align: left">Login:</td>
            <td style="text-align: left"><?= $this->dados["login"] ?></td>
        </tr>
        <tr>
            <td style="text-align: left">Email:</td>
            <td style="text-align: left"><?= $this->dados["email"] ?></td>
        </tr>         
    </tbody>
</table>

<form method="<?= $this->form->getMethod() ?>" action="<?= $this->form->getAction() ?>" class="Form" id="form">
    <h2>Editar</h2>
    <dl>

        <dt><label for="senha"><?= $this->form->senha->getLabel() ?></label></dt>
        <dd><?= $this->form->senha ?></dd>
        <dt><label for="senha2"><?= $this->form->senha2->getLabel() ?></label></dt>
        <dd><?= $this->form->senha2 ?></dd>
        <dt><?= $this->form->id ?></dt>
        <dd><?= $this->form->submit ?></dd>
    </dl>
</form>
