<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Portalzend - Acesso Negado</title>
        <style type="text/css">
            *{margin: 0px;padding: 0px;}
            #geral{
                
                width:800px;
                margin: 20% auto;
                background: #eeeeee;
                padding: 25px;
                font-size: 12px;
                font-family: cambria;
                box-shadow: 0px 1px 20px #333;
                border-radius: 5px;
            }
            #geral p{
                padding: 10px;
            }
        </style>
    </head>
    <body>
        <div id="geral">
            <h1>Ops! você não tem permissão para acessar está página !</h1>
            <p>
                Entre em contato com o administrador do sistema.
                <a href="mailto:hugoamac@live.com"/>hugoamac@live.com</a>
            </p>
        </div>
    </body>
</html>