<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Area de Acesso</title>
        <link href="/css/stilo_adm.css" rel="stylesheet" type="text/css"/>


        <!-- JQUERY -->
        <script src="/library_js/jquery.js" type="text/javascript"></script>
        <!-- JQUERY UI-->
        <script src="/library_js/jquery_ui/js/jquery_ui.js" type="text/javascript"></script>
        <link href="/library_js/jquery_ui/css/smoothness/jquery_ui.css" rel="stylesheet" type="text/css"/>
        <!-- VALIDATE-->
        <script src="/library_js/jquery-validate/jquery.validate.js" type="text/javascript"></script>
        <!-- MY SCRIPTS -->
        <script src="/scripts_js/admin/admin_geral.js" type="text/javascript"></script>

        <style type="text/css">
            #BodyLogin{

                width:420px;
                margin:20% auto;

            }
            .login{
                background:#E9F1F4;
                border:solid 1px #ccc;
                border-radius: 3px 3px 0 0;
                font-size:12px;
                box-shadow: 0px 1px 5px #ccc;

            }
            .login h2{
                color: white;
                font-size: 16px;
                font-weight: bold;
                background: #829AA8;
                background: -moz-linear-gradient(#829AA8, #405A6A);
                background: -webkit-linear-gradient(#829AA8, #405A6A);
                -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='#829aa8', endColorstr='#405a6a')";
                border: 1px solid #677C89;
                border-bottom-color: #6B808D;
                border-radius: 3px 3px 0 0;
                text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.7);
                margin: 0;
                padding: 8px 18px;
            }
            .login input[type=text],input[type=password]{

                border:solid 1px #ccc;
                width:280px;
                padding:5px;
                background: #ffffff !important;
            }
            .login button{
                display: inline-block;
                height: 34px;
                padding: 0;
                position: relative;
                top: 1px;
                margin-left: 10px;
                font-family: Helvetica, arial, freesans, clean, sans-serif;
                font-weight: bold;
                font-size: 12px;
                color: #333;
                text-shadow: 1px 1px 0 white;
                white-space: nowrap;
                border: none;
                overflow: visible;
                background: white;
                background: -moz-linear-gradient(white, #E1E1E1);
                background: -webkit-linear-gradient(white, #E1E1E1);
                -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr='white', endColorstr='#e1e1e1')";
                border-bottom: 1px solid #EBEBEB;
                border-radius: 4px;
                box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3);
                cursor: pointer;
                margin-left: 1px;
                padding: 0px 13px;
                -webkit-font-smoothing: subpixel-antialiased !important;		
            }
        </style>
        <script type="text/javascript">
            $(function(){
                $("#BodyLogin").css({'cursor':'move'}).draggable();
                
            })
    </script>

    </head>
    <body>
        <div id="BodyLogin">

            <? if (!empty($this->message)): ?>
                <p class="aviso_erro"><?= $this->escape($this->message) ?></p>
            <? else: ?>
                <p class="aviso_alerta" style="display:none"></p>
            <? endif; ?>

            <form method="post" action="" id="form" class="Form login">
                <h2>Área de Acesso</h2>
                <dl style="text-align: center">
                    <dt><label for="login"><?= $this->form->login->getLabel() ?></label></dt>
                    <dd><?= $this->form->login ?></dd>

                    <dt><label for="senha"><?= $this->form->senha->getLabel() ?></label></dt>
                    <dd><?= $this->form->senha ?></dd>

                    <dt></dt>
                    <dd>
                        <?= $this->form->submit ?>
                    </dd>
                </dl>
            </form>

        </div>

    </body>
</html>




